[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --timeout 30 --workers 2 --threads 4"
healthcheckPath = "/accounts/login/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[release]
cmd = "bash -c \"python manage.py migrate --noinput && python manage.py collectstatic --noinput && (python manage.py seed_data --noinput || true)\""
