# Generated by Django 6.0.6 on 2026-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
