# Generated by Django 5.2.15 on 2026-06-25 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('federal_ss_rate', models.DecimalField(decimal_places=4, default=0.062, max_digits=5)),
                ('federal_ss_wage_base', models.DecimalField(decimal_places=2, default=168600, max_digits=10)),
                ('federal_medicare_rate', models.DecimalField(decimal_places=4, default=0.0145, max_digits=5)),
                ('federal_futa_rate', models.DecimalField(decimal_places=4, default=0.006, max_digits=5)),
                ('nc_income_tax_rate', models.DecimalField(decimal_places=4, default=0.045, max_digits=5)),
                ('nc_unemployment_rate', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('nc_unemployment_wage_base', models.DecimalField(decimal_places=2, default=29600, max_digits=10)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='Paystub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('federal_income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nc_state_income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('social_security', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nc_unemployment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aflac', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retirement_401k', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_support', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_account', models.CharField(blank=True, default='', max_length=100)),
                ('deposit_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paystubs', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystubs', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['-payroll_run__pay_date', 'employee__last_name'],
            },
        ),
    ]
