from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_lineitem_blank_desc'),
        ('standard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20, default='monthly', choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')])),
                ('status', models.CharField(max_length=20, default='active', choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_invoice_date', models.DateField()),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='core.customer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='core.division')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='RecurringInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('recurring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='premium.recurringinvoice')),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['name'], 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/')),
                ('status', models.CharField(max_length=20, default='pending', choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reimbursed', 'Reimbursed')])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='premium.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.division')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='standard.job')),
            ],
            options={'ordering': ['-date', '-id']},
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=20, default='checking', choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('line_of_credit', 'Line of Credit')])),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.division')),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=20, default='unmatched', choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('reconciled', 'Reconciled'), ('excluded', 'Excluded')])),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment')),
                ('matched_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='premium.expense')),
                ('notes', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='premium.bankaccount')),
            ],
            options={'ordering': ['-date', '-id']},
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('vendor', models.CharField(max_length=200)),
                ('vendor_address', models.TextField(blank=True)),
                ('vendor_email', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20, default='draft', choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')])),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.division')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='standard.job')),
            ],
            options={'ordering': ['-order_date', '-id']},
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='premium.purchaseorder')),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('entity_type', models.CharField(max_length=20, default='individual', choices=[('individual', 'Individual'), ('llc', 'LLC'), ('s_corp', 'S-Corp'), ('c_corp', 'C-Corp'), ('partnership', 'Partnership')])),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('w9_on_file', models.BooleanField(default=False)),
                ('w9_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ContractorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_1099_reportable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='premium.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_payments', to='core.division')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_payments', to='standard.job')),
            ],
            options={'ordering': ['-date', '-id']},
        ),
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=20, choices=[('w2', 'W-2 Wage and Tax Statement'), ('1099_nec', '1099-NEC Nonemployee Compensation'), ('1099_misc', '1099-MISC Miscellaneous Income')])),
                ('tax_year', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_tax_id', models.CharField(blank=True, max_length=50)),
                ('recipient_address', models.TextField(blank=True)),
                ('total_compensation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('federal_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('social_security_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicare_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(max_length=20, default='draft', choices=[('draft', 'Draft'), ('final', 'Final'), ('filed', 'Filed')])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-tax_year', 'form_type'], 'unique_together': {('form_type', 'tax_year', 'recipient_name')}},
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=20, choices=[('customers', 'Customers'), ('employees', 'Employees'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('expenses', 'Expenses'), ('all', 'All Data')])),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('status', models.CharField(max_length=20, default='pending', choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')])),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=20, default='draft', choices=[('draft', 'Draft'), ('sent', 'Sent for Signature'), ('signed', 'Signed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True)),
                ('signer_name', models.CharField(blank=True, max_length=200)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.customer')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.division')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EstimateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('base_labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_templates', to='core.division')),
            ],
            options={'ordering': ['name']},
        ),
    ]
